require("nvim-tree").setup({
    hijack_cursor = true,
    sync_root_with_cwd = true,
    filters = {
        custom = {
            '.aux',
            '.fdb_latexmk ',
            '.fls ',
            '.synctex.gz ',
        }
    },
    ignore_ft_on_setup = {
        "startify",
        "dashboard",
        "alpha",
    },
    renderer = {
        indent_width = 2,
        indent_markers = {
            enable = true,
        },
        icons = {
            webdev_colors = true,
            git_placement = "after",
            padding = " ",
            symlink_arrow = " ➛ ",
            show = {
                file = true,
                folder = true,
                folder_arrow = true,
                git = true,
            },
            glyphs = {
                default = "",
                symlink = "",
                folder = {
                    default = "",
                    open = "",
                    empty = "",
                    empty_open = "",
                    symlink = "",
                    symlink_open = "",
                },
                git = {
                    unstaged = "",
                    staged = "S",
                    unmerged = "",
                    renamed = "➜",
                    untracked = "U",
                    deleted = "",
                    ignored = "◌",
                },
            },
        },
    },
    view = {
        width = 25,
        hide_root_folder = true,
        signcolumn = "yes",
        mappings = {
            list = {
                { key = { "<CR>", "o", "<2-LeftMouse>" }, action = "edit" },
                { key = "<C-e>", action = "edit_in_place" },
                { key = "O", action = "edit_no_picker" },
                { key = { "c", "<2-RightMouse>" }, action = "cd" },
                { key = "s", action = "vsplit" },
                { key = "i", action = "split" },
                { key = "t", action = "tabnew" },
                { key = "<", action = "prev_sibling" },
                { key = ">", action = "next_sibling" },
                { key = "P", action = "parent_node" },
                { key = "x", action = "close_node" },
                { key = "<Tab>", action = "preview" },
                { key = "K", action = "first_sibling" },
                { key = "J", action = "last_sibling" },
                { key = "H", action = "toggle_git_ignored" },
                { key = "I", action = "toggle_dotfiles" },
                { key = "U", action = "toggle_custom" },
                { key = "R", action = "refresh" },
                { key = "a", action = "create" },
                { key = "d", action = "remove" },
                { key = "D", action = "trash" },
                { key = "r", action = "rename" },
                { key = "<C-r>", action = "full_rename" },
                { key = "X", action = "cut" },
                { key = "C", action = "copy" },
                { key = "p", action = "paste" },
                { key = "y", action = "copy_name" },
                { key = "Y", action = "copy_path" },
                { key = "gy", action = "copy_absolute_path" },
                { key = "[e", action = "prev_diag_item" },
                { key = "[c", action = "prev_git_item" },
                { key = "]e", action = "next_diag_item" },
                { key = "]c", action = "next_git_item" },
                { key = "u", action = "dir_up" },
                { key = "<C-s>", action = "system_open" },
                { key = "f", action = "live_filter" },
                { key = "F", action = "clear_live_filter" },
                { key = "q", action = "close" },
                { key = "<C-x>", action = "collapse_all" },
                { key = "<C-o>", action = "expand_all" },
                { key = "S", action = "search_node" },
                { key = ".", action = "run_file_command" },
                { key = "<C-k>", action = "toggle_file_info" },
                { key = "g?", action = "toggle_help" },
                { key = "m", action = "toggle_mark" },
                { key = "bmv", action = "bulk_move" },
            }
        }
    }
})
